TABLE_ (WOW_PLAYER_RECORDS)
   INT_    (WOW_PLAYER_ID) PRIMARY_KEY AUTO_INCREMENT
   STRING_ (WOW_NAME,200) SQLDEFAULT("") NOT_NULL UNIQUE
END_TABLE

TABLE_ (WOW_MOTIFS)
	INT_ (WOW_MOTIFS_ID) PRIMARY_KEY AUTO_INCREMENT
	STRING_(WOW_MOTIF,300) SQLDEFAULT("") NOT_NULL
	INT_ (WOW_MOTIFS_WOW_PLAYER_RECORDS_ID)REFERENCES_CASCADE_(WOW_PLAYER_RECORDS,WOW_PLAYER_ID)
END_TABLE